/**
 * @fileoverview gRPC-Web generated client stub for chat
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.0
// source: proto/chat.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.chat = require('./chat_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chat.UserServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chat.UserServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.RegisterRequest,
 *   !proto.chat.RegisterResponse>}
 */
const methodDescriptor_UserService_Register = new grpc.web.MethodDescriptor(
  '/chat.UserService/Register',
  grpc.web.MethodType.UNARY,
  proto.chat.RegisterRequest,
  proto.chat.RegisterResponse,
  /**
   * @param {!proto.chat.RegisterRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.RegisterResponse.deserializeBinary
);


/**
 * @param {!proto.chat.RegisterRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.RegisterResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.RegisterResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.UserServiceClient.prototype.register =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.UserService/Register',
      request,
      metadata || {},
      methodDescriptor_UserService_Register,
      callback);
};


/**
 * @param {!proto.chat.RegisterRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.RegisterResponse>}
 *     Promise that resolves to the response
 */
proto.chat.UserServicePromiseClient.prototype.register =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.UserService/Register',
      request,
      metadata || {},
      methodDescriptor_UserService_Register);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.LoginRequest,
 *   !proto.chat.LoginResponse>}
 */
const methodDescriptor_UserService_Login = new grpc.web.MethodDescriptor(
  '/chat.UserService/Login',
  grpc.web.MethodType.UNARY,
  proto.chat.LoginRequest,
  proto.chat.LoginResponse,
  /**
   * @param {!proto.chat.LoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.LoginResponse.deserializeBinary
);


/**
 * @param {!proto.chat.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.LoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.LoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.UserServiceClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.UserService/Login',
      request,
      metadata || {},
      methodDescriptor_UserService_Login,
      callback);
};


/**
 * @param {!proto.chat.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.LoginResponse>}
 *     Promise that resolves to the response
 */
proto.chat.UserServicePromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.UserService/Login',
      request,
      metadata || {},
      methodDescriptor_UserService_Login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.GetUserInfoRequest,
 *   !proto.chat.UserInfo>}
 */
const methodDescriptor_UserService_GetUserInfo = new grpc.web.MethodDescriptor(
  '/chat.UserService/GetUserInfo',
  grpc.web.MethodType.UNARY,
  proto.chat.GetUserInfoRequest,
  proto.chat.UserInfo,
  /**
   * @param {!proto.chat.GetUserInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.UserInfo.deserializeBinary
);


/**
 * @param {!proto.chat.GetUserInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.UserInfo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.UserInfo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.UserServiceClient.prototype.getUserInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.UserService/GetUserInfo',
      request,
      metadata || {},
      methodDescriptor_UserService_GetUserInfo,
      callback);
};


/**
 * @param {!proto.chat.GetUserInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.UserInfo>}
 *     Promise that resolves to the response
 */
proto.chat.UserServicePromiseClient.prototype.getUserInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.UserService/GetUserInfo',
      request,
      metadata || {},
      methodDescriptor_UserService_GetUserInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.UpdateUserStatusRequest,
 *   !proto.chat.Empty>}
 */
const methodDescriptor_UserService_UpdateUserStatus = new grpc.web.MethodDescriptor(
  '/chat.UserService/UpdateUserStatus',
  grpc.web.MethodType.UNARY,
  proto.chat.UpdateUserStatusRequest,
  proto.chat.Empty,
  /**
   * @param {!proto.chat.UpdateUserStatusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.Empty.deserializeBinary
);


/**
 * @param {!proto.chat.UpdateUserStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.UserServiceClient.prototype.updateUserStatus =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.UserService/UpdateUserStatus',
      request,
      metadata || {},
      methodDescriptor_UserService_UpdateUserStatus,
      callback);
};


/**
 * @param {!proto.chat.UpdateUserStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.Empty>}
 *     Promise that resolves to the response
 */
proto.chat.UserServicePromiseClient.prototype.updateUserStatus =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.UserService/UpdateUserStatus',
      request,
      metadata || {},
      methodDescriptor_UserService_UpdateUserStatus);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chat.RoomServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chat.RoomServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.CreateRoomRequest,
 *   !proto.chat.RoomInfo>}
 */
const methodDescriptor_RoomService_CreateRoom = new grpc.web.MethodDescriptor(
  '/chat.RoomService/CreateRoom',
  grpc.web.MethodType.UNARY,
  proto.chat.CreateRoomRequest,
  proto.chat.RoomInfo,
  /**
   * @param {!proto.chat.CreateRoomRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.RoomInfo.deserializeBinary
);


/**
 * @param {!proto.chat.CreateRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.RoomInfo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.RoomInfo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.RoomServiceClient.prototype.createRoom =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.RoomService/CreateRoom',
      request,
      metadata || {},
      methodDescriptor_RoomService_CreateRoom,
      callback);
};


/**
 * @param {!proto.chat.CreateRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.RoomInfo>}
 *     Promise that resolves to the response
 */
proto.chat.RoomServicePromiseClient.prototype.createRoom =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.RoomService/CreateRoom',
      request,
      metadata || {},
      methodDescriptor_RoomService_CreateRoom);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.JoinRoomRequest,
 *   !proto.chat.RoomInfo>}
 */
const methodDescriptor_RoomService_JoinRoom = new grpc.web.MethodDescriptor(
  '/chat.RoomService/JoinRoom',
  grpc.web.MethodType.UNARY,
  proto.chat.JoinRoomRequest,
  proto.chat.RoomInfo,
  /**
   * @param {!proto.chat.JoinRoomRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.RoomInfo.deserializeBinary
);


/**
 * @param {!proto.chat.JoinRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.RoomInfo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.RoomInfo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.RoomServiceClient.prototype.joinRoom =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.RoomService/JoinRoom',
      request,
      metadata || {},
      methodDescriptor_RoomService_JoinRoom,
      callback);
};


/**
 * @param {!proto.chat.JoinRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.RoomInfo>}
 *     Promise that resolves to the response
 */
proto.chat.RoomServicePromiseClient.prototype.joinRoom =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.RoomService/JoinRoom',
      request,
      metadata || {},
      methodDescriptor_RoomService_JoinRoom);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.LeaveRoomRequest,
 *   !proto.chat.Empty>}
 */
const methodDescriptor_RoomService_LeaveRoom = new grpc.web.MethodDescriptor(
  '/chat.RoomService/LeaveRoom',
  grpc.web.MethodType.UNARY,
  proto.chat.LeaveRoomRequest,
  proto.chat.Empty,
  /**
   * @param {!proto.chat.LeaveRoomRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.Empty.deserializeBinary
);


/**
 * @param {!proto.chat.LeaveRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.RoomServiceClient.prototype.leaveRoom =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.RoomService/LeaveRoom',
      request,
      metadata || {},
      methodDescriptor_RoomService_LeaveRoom,
      callback);
};


/**
 * @param {!proto.chat.LeaveRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.Empty>}
 *     Promise that resolves to the response
 */
proto.chat.RoomServicePromiseClient.prototype.leaveRoom =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.RoomService/LeaveRoom',
      request,
      metadata || {},
      methodDescriptor_RoomService_LeaveRoom);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.GetRoomInfoRequest,
 *   !proto.chat.RoomInfo>}
 */
const methodDescriptor_RoomService_GetRoomInfo = new grpc.web.MethodDescriptor(
  '/chat.RoomService/GetRoomInfo',
  grpc.web.MethodType.UNARY,
  proto.chat.GetRoomInfoRequest,
  proto.chat.RoomInfo,
  /**
   * @param {!proto.chat.GetRoomInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.RoomInfo.deserializeBinary
);


/**
 * @param {!proto.chat.GetRoomInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.RoomInfo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.RoomInfo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.RoomServiceClient.prototype.getRoomInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.RoomService/GetRoomInfo',
      request,
      metadata || {},
      methodDescriptor_RoomService_GetRoomInfo,
      callback);
};


/**
 * @param {!proto.chat.GetRoomInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.RoomInfo>}
 *     Promise that resolves to the response
 */
proto.chat.RoomServicePromiseClient.prototype.getRoomInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.RoomService/GetRoomInfo',
      request,
      metadata || {},
      methodDescriptor_RoomService_GetRoomInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.ListRoomsRequest,
 *   !proto.chat.ListRoomsResponse>}
 */
const methodDescriptor_RoomService_ListRooms = new grpc.web.MethodDescriptor(
  '/chat.RoomService/ListRooms',
  grpc.web.MethodType.UNARY,
  proto.chat.ListRoomsRequest,
  proto.chat.ListRoomsResponse,
  /**
   * @param {!proto.chat.ListRoomsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.ListRoomsResponse.deserializeBinary
);


/**
 * @param {!proto.chat.ListRoomsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.ListRoomsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.ListRoomsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.RoomServiceClient.prototype.listRooms =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.RoomService/ListRooms',
      request,
      metadata || {},
      methodDescriptor_RoomService_ListRooms,
      callback);
};


/**
 * @param {!proto.chat.ListRoomsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.ListRoomsResponse>}
 *     Promise that resolves to the response
 */
proto.chat.RoomServicePromiseClient.prototype.listRooms =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.RoomService/ListRooms',
      request,
      metadata || {},
      methodDescriptor_RoomService_ListRooms);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.ListRoomUsersRequest,
 *   !proto.chat.ListUsersResponse>}
 */
const methodDescriptor_RoomService_ListRoomUsers = new grpc.web.MethodDescriptor(
  '/chat.RoomService/ListRoomUsers',
  grpc.web.MethodType.UNARY,
  proto.chat.ListRoomUsersRequest,
  proto.chat.ListUsersResponse,
  /**
   * @param {!proto.chat.ListRoomUsersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.ListUsersResponse.deserializeBinary
);


/**
 * @param {!proto.chat.ListRoomUsersRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.ListUsersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.ListUsersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.RoomServiceClient.prototype.listRoomUsers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.RoomService/ListRoomUsers',
      request,
      metadata || {},
      methodDescriptor_RoomService_ListRoomUsers,
      callback);
};


/**
 * @param {!proto.chat.ListRoomUsersRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.ListUsersResponse>}
 *     Promise that resolves to the response
 */
proto.chat.RoomServicePromiseClient.prototype.listRoomUsers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.RoomService/ListRoomUsers',
      request,
      metadata || {},
      methodDescriptor_RoomService_ListRoomUsers);
};


module.exports = proto.chat;

